remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Maya Hatoum
description: I am a healthcare data analyst with 2 years of experience and 2 years of experience in healthcare. During this time, I have had the opportunity to gain experience with 3 EMR systems, strengthen my analytical skills and advance my knowledge of medical terminology and clinical coding standards. I have also worked with a variety of stakeholders, including medical directors, healthcare providers, entrepreneurs and state health planners to play a key role in clinical decision-making.

I became well-versed in softwares such as Tableau, Python, R, SQL, MS Excel and have demonstrated efficient analytical techniques such as data cleaning, dashboard building, and report writing. My portfolio includes health and non-clinical projects showcasing my ability to organize and present data for stakeholders to understand and take action.

My ultimate career goal is to grow with a Healthcare company and contribute to meaningful data management, analysis and/or research that makes a difference in the lives of patients and communities, ultimately improving health outcomes for all. 

Thank you for considering me as a candidate, I look forward to hearing from you soon.

 
